subscriptions:
#    Binance:
#        instruments:
#          - ETH/BTC
#          - XRP/BTC
#        depth: 10
#    FTX:
#        instruments:
#          - ETH-PERP
#        depth: 10
    Binance:
        instruments:
          - ETH/USDT
        depth: 10
#        type: swap

#    Bitmex:
#        instruments:
#            - ETHUSD

handlers:
    sql:
        connection: "sqlite:///./order_book.db"
        is_rotate: True
        rotate_frequency: "%Y%m%d%H%M"
