subscriptions:
    BinanceFutures:
        instruments:
          - ETH-USDT
          - XRP-USDT
        depth: 10
        type: futures

#    Bitmex:
#        instruments:
#            - ETHUSD

handlers:
#    sql:
#        connection: "sqlite:///../order_book.db"
#        is_rotate: True
#        rotate_frequency: "%Y%m%d%H%M"
    zmq:
        connection: "tcp://*:9124"
