subscriptions:
    BinanceFutures:
        instruments:
            - BTC-USDT
        #          - XRP-USDT
        depth: 10
        type: futures

#    OKEx:
#        instruments:
#            - BTC-USDT-SWAP
#        depth: 10
#        type: swap

handlers:
    #    sql:
    #        connection: "sqlite:///../order_book.db"
    #        is_rotate: True
    #        rotate_frequency: "%Y%m%d%H%M"
    zmq:
        connection: "tcp://*:9124"
